In [4]:
import os

In [6]:
os.chdir("C:\\Users\\Adhvaidh\\Desktop\\ML DATASETS")

In [8]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn 
import seaborn as sns

In [10]:
ds=pd.read_csv("50_Startups.csv")

In [12]:
ds.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
len(ds)

50

In [17]:
pd.DataFrame(ds).isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [81]:
a=ds.iloc[:,:-1].values

In [43]:
a

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 294919.57, 'Florida'],
       [86419.7, 153514.11, 0.0, 'New York'],
       [76253.86, 113867.3, 298664.47, 'California'],
       [78389.47, 153773.43, 299737.29, 'New York'],
       [73994.56, 122782.75, 303319.26, 'Florida'],
       [67532.53, 105751.03, 304768.73, 'Florida'],
       [77044.01, 99281.34, 140574.81, 'New York'],
       [64664.71, 139553.16, 137962.62, 'California'],
       [75328.87, 144135.98, 134050.07, 'Florida'],
       [72107.6, 127864.55, 353183.81, 'New York'],
       [66051.52, 182645.56, 118148.2, 'Florida'],
       [65605.48, 153032.06, 107138.38, 'New York'],
       [61994.48, 115641.28, 91131.24, 'Florida'],
       [61136.38, 152701.92, 88218.23, 'New York'],
       [63408.86, 129219.61, 46085.25, 'California'],
       [55493.95, 103057.49, 214634.81, 'Florida'],
       [46426.07, 157693.92, 210797.67, 'California'],
       [46014.02, 85047.44, 205517.64, 'New York'],
       [28663.76, 127056.21, 201126.82, 'Florida'],
       [44069.95, 51283.14, 197029.42, 'California'],
       [20229.59, 65947.93, 185265.1, 'New York'],
       [38558.51, 82982.09, 174999.3, 'California'],
       [28754.33, 118546.05, 172795.67, 'California'],
       [27892.92, 84710.77, 164470.71, 'Florida'],
       [23640.93, 96189.63, 148001.11, 'California'],
       [15505.73, 127382.3, 35534.17, 'New York'],
       [22177.74, 154806.14, 28334.72, 'California'],
       [1000.23, 124153.04, 1903.93, 'New York'],
       [1315.46, 115816.21, 297114.46, 'Florida'],
       [0.0, 135426.92, 0.0, 'California'],
       [542.05, 51743.15, 0.0, 'New York'],
       [0.0, 116983.8, 45173.06, 'California']], dtype=object)

In [82]:
b=ds.iloc[:,4].values

In [45]:
b

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

# Encoding concept

In [83]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_a=LabelEncoder()
a[:,3]=labelencoder_a.fit_transform(a[:,3])

In [47]:
a

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 303319.26, 1],
       [67532.53, 105751.03, 304768.73, 1],
       [77044.01, 99281.34, 140574.81, 2],
       [64664.71, 139553.16, 137962.62, 0],
       [75328.87, 144135.98, 134050.07, 1],
       [72107.6, 127864.55, 353183.81, 2],
       [66051.52, 182645.56, 118148.2, 1],
       [65605.48, 153032.06, 107138.38, 2],
       [61994.48, 115641.28, 91131.24, 1],
       [61136.38, 152701.92, 88218.23, 2],
       [63408.86, 129219.61, 46085.25, 0],
       [55493.95, 103057.49, 214634.81, 1],
       [46426.07, 157693.92, 210797.67, 0],
       [46014.02, 85047.44, 205517.64, 2],
       [28663.76, 127056.21, 201126.82, 1],
       [44069.95, 51283.14, 197029.42, 0],
       [20229.59, 65947.93, 185265.1, 2],
       [38558.51, 82982.09, 174999.3, 0],
       [28754.33, 118546.05, 172795.67, 0],
       [27892.92, 84710.77, 164470.71, 1],
       [23640.93, 96189.63, 148001.11, 0],
       [15505.73, 127382.3, 35534.17, 2],
       [22177.74, 154806.14, 28334.72, 0],
       [1000.23, 124153.04, 1903.93, 2],
       [1315.46, 115816.21, 297114.46, 1],
       [0.0, 135426.92, 0.0, 0],
       [542.05, 51743.15, 0.0, 2],
       [0.0, 116983.8, 45173.06, 0]], dtype=object)

In [84]:
onehotencoder=OneHotEncoder(categorical_features=[3])
a=onehotencoder.fit_transform(a).toarray()

C:\Users\Adhvaidh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Adhvaidh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [85]:
pd.DataFrame(a)

      0    1    2          3          4          5
0   0.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  0.0  1.0   78389.47  153773.43  299737.29
22  0.0  1.0  0.0   73994.56  122782.75  303319.26
23  0.0  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  0.0  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  0.0  1.0   72107.60  127864.55  353183.81
28  0.0  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  0.0  1.0   65605.48  153032.06  107138.38
30  0.0  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  0.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  0.0  1.0   46014.02   85047.44  205517.64
36  0.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  0.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  0.0  1.0    1000.23  124153.04    1903.93
46  0.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  0.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

In [86]:
a=a[:,1:]
pd.DataFrame(a)

      0    1          2          3          4
0   0.0  1.0  165349.20  136897.80  471784.10
1   0.0  0.0  162597.70  151377.59  443898.53
2   1.0  0.0  153441.51  101145.55  407934.54
3   0.0  1.0  144372.41  118671.85  383199.62
4   1.0  0.0  142107.34   91391.77  366168.42
5   0.0  1.0  131876.90   99814.71  362861.36
6   0.0  0.0  134615.46  147198.87  127716.82
7   1.0  0.0  130298.13  145530.06  323876.68
8   0.0  1.0  120542.52  148718.95  311613.29
9   0.0  0.0  123334.88  108679.17  304981.62
10  1.0  0.0  101913.08  110594.11  229160.95
11  0.0  0.0  100671.96   91790.61  249744.55
12  1.0  0.0   93863.75  127320.38  249839.44
13  0.0  0.0   91992.39  135495.07  252664.93
14  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  1.0  114523.61  122616.84  261776.23
16  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  1.0   94657.16  145077.58  282574.31
18  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  1.0   86419.70  153514.11       0.00
20  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  1.0   78389.47  153773.43  299737.29
22  1.0  0.0   73994.56  122782.75  303319.26
23  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  1.0   77044.01   99281.34  140574.81
25  0.0  0.0   64664.71  139553.16  137962.62
26  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  1.0   72107.60  127864.55  353183.81
28  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  1.0   65605.48  153032.06  107138.38
30  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  1.0   61136.38  152701.92   88218.23
32  0.0  0.0   63408.86  129219.61   46085.25
33  1.0  0.0   55493.95  103057.49  214634.81
34  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  1.0   46014.02   85047.44  205517.64
36  1.0  0.0   28663.76  127056.21  201126.82
37  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  1.0   20229.59   65947.93  185265.10
39  0.0  0.0   38558.51   82982.09  174999.30
40  0.0  0.0   28754.33  118546.05  172795.67
41  1.0  0.0   27892.92   84710.77  164470.71
42  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  1.0   15505.73  127382.30   35534.17
44  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  1.0    1000.23  124153.04    1903.93
46  1.0  0.0    1315.46  115816.21  297114.46
47  0.0  0.0       0.00  135426.92       0.00
48  0.0  1.0     542.05   51743.15       0.00
49  0.0  0.0       0.00  116983.80   45173.06

# Spritting train-test dataset.
## a=independent variable, b=dependant variable.

In [93]:
from sklearn.model_selection import train_test_split
a_train, a_test, b_train, b_test= train_test_split(a,b,test_size=0.2,random_state=0)

In [94]:
from sklearn.model_selection import train_test_split

# Linear Regression

In [95]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(a_train, b_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
regressor.coef_

array([-9.59284160e+02,  6.99369053e+02,  7.73467193e-01,  3.28845975e-02,
        3.66100259e-02])

In [97]:
regressor.intercept_

42554.16761772438

# Prediction

In [98]:
b_pred=regressor.predict(a_test)

# Accuracy

In [100]:
from sklearn.metrics import r2_score
r2_score(b_test,b_pred)

0.9347068473282446

# Stats value

In [113]:
import statsmodels.regression.linear_model as sm

In [104]:
#y=mx + c

In [114]:
a_train=np.append(arr=a_train, values=np.ones((40,1)).astype(int),axis=1)

In [115]:
pd.DataFrame(a_train)

      0    1          2          3          4    5    6    7
0   1.0  0.0   55493.95  103057.49  214634.81  1.0  1.0  1.0
1   0.0  1.0   46014.02   85047.44  205517.64  1.0  1.0  1.0
2   1.0  0.0   75328.87  144135.98  134050.07  1.0  1.0  1.0
3   0.0  0.0   46426.07  157693.92  210797.67  1.0  1.0  1.0
4   1.0  0.0   91749.16  114175.79  294919.57  1.0  1.0  1.0
5   1.0  0.0  130298.13  145530.06  323876.68  1.0  1.0  1.0
6   1.0  0.0  119943.24  156547.42  256512.92  1.0  1.0  1.0
7   0.0  1.0    1000.23  124153.04    1903.93  1.0  1.0  1.0
8   0.0  1.0     542.05   51743.15       0.00  1.0  1.0  1.0
9   0.0  1.0   65605.48  153032.06  107138.38  1.0  1.0  1.0
10  0.0  1.0  114523.61  122616.84  261776.23  1.0  1.0  1.0
11  1.0  0.0   61994.48  115641.28   91131.24  1.0  1.0  1.0
12  0.0  0.0   63408.86  129219.61   46085.25  1.0  1.0  1.0
13  0.0  0.0   78013.11  121597.55  264346.06  1.0  1.0  1.0
14  0.0  0.0   23640.93   96189.63  148001.11  1.0  1.0  1.0
15  0.0  0.0   76253.86  113867.30  298664.47  1.0  1.0  1.0
16  0.0  1.0   15505.73  127382.30   35534.17  1.0  1.0  1.0
17  0.0  1.0  120542.52  148718.95  311613.29  1.0  1.0  1.0
18  0.0  0.0   91992.39  135495.07  252664.93  1.0  1.0  1.0
19  0.0  0.0   64664.71  139553.16  137962.62  1.0  1.0  1.0
20  0.0  1.0  131876.90   99814.71  362861.36  1.0  1.0  1.0
21  0.0  1.0   94657.16  145077.58  282574.31  1.0  1.0  1.0
22  0.0  0.0   28754.33  118546.05  172795.67  1.0  1.0  1.0
23  0.0  0.0       0.00  116983.80   45173.06  1.0  1.0  1.0
24  0.0  0.0  162597.70  151377.59  443898.53  1.0  1.0  1.0
25  1.0  0.0   93863.75  127320.38  249839.44  1.0  1.0  1.0
26  0.0  0.0   44069.95   51283.14  197029.42  1.0  1.0  1.0
27  0.0  1.0   77044.01   99281.34  140574.81  1.0  1.0  1.0
28  0.0  0.0  134615.46  147198.87  127716.82  1.0  1.0  1.0
29  1.0  0.0   67532.53  105751.03  304768.73  1.0  1.0  1.0
30  1.0  0.0   28663.76  127056.21  201126.82  1.0  1.0  1.0
31  0.0  1.0   78389.47  153773.43  299737.29  1.0  1.0  1.0
32  0.0  1.0   86419.70  153514.11       0.00  1.0  1.0  1.0
33  0.0  0.0  123334.88  108679.17  304981.62  1.0  1.0  1.0
34  0.0  0.0   38558.51   82982.09  174999.30  1.0  1.0  1.0
35  1.0  0.0    1315.46  115816.21  297114.46  1.0  1.0  1.0
36  0.0  1.0  144372.41  118671.85  383199.62  1.0  1.0  1.0
37  0.0  1.0  165349.20  136897.80  471784.10  1.0  1.0  1.0
38  0.0  0.0       0.00  135426.92       0.00  1.0  1.0  1.0
39  0.0  0.0   22177.74  154806.14   28334.72  1.0  1.0  1.0

In [116]:
regressor_nm=sm.OLS(endog=b_train, exog=a_train).fit()

In [117]:
regressor_nm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     129.7
Date:                Sat, 09 Nov 2019   Prob (F-statistic):           3.91e-21
Time:                        11:30:34   Log-Likelihood:                -421.10
No. Observations:                  40   AIC:                             854.2
Df Residuals:                      34   BIC:                             864.3
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          -959.2842   4038.108     -0.238      0.814   -9165.706    7247.138
x2           699.3691   3661.563      0.191      0.850   -6741.822    8140.560
x3             0.7735      0.055     14.025      0.000       0.661       0.886
x4             0.0329      0.066      0.495      0.624      -0.102       0.168
x5             0.0366      0.019      1.884      0.068      -0.003       0.076
const       1.418e+04   2786.179      5.091      0.000    8522.525    1.98e+04
x6          1.418e+04   2786.179      5.091      0.000    8522.525    1.98e+04
x7          1.418e+04   2786.179      5.091      0.000    8522.525    1.98e+04
==============================================================================
Omnibus:                       15.823   Durbin-Watson:                   2.468
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               23.231
Skew:                          -1.094   Prob(JB):                     9.03e-06
Kurtosis:                       6.025   Cond. No.                     9.18e+37
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.54e-64. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""